name: CI
on:
  pull_request:
    branches: [ "dev", "test" ]
  push:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Run your test suite here (e.g., pytest, npm test)"
