name: Staging Deploy
on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy staging
        run: echo "Deploy to staging environment here"
